import './globals.css'
import { Inter } from 'next/font/google'
import GlobalProvider from '@/components/GlobalProvider/GlobalProvider';

const inter = Inter({ subsets: ['cyrillic'] })

export const metadata = {
  metadataBase: new URL('https://stfaki.vercel.app'),
  title: {
    template: '%s | stfaki',
    default: 'ФАКТ'
  },
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
    shortcut: '/favicon.ico',
    apple: '/favicon.ico'
  },
  openGraph: {
    images: '/opengraph-image',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={inter.className}>
      <GlobalProvider>
        {children}
      </GlobalProvider>
      </body>
    </html>
  )
}