"use client";

import './globals.css'
import { Inter } from 'next/font/google'
import { Sidebar } from '@/components/Sidebar/Sidebar'
import { useEffect, useState } from 'react';

const inter = Inter({ subsets: ['cyrillic'] })

export const metadata = {
  title: {
    template: '%s | stfaki',
    default: 'ФАКТ'
  },
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
    shortcut: '/favicon.ico',
    apple: '/favicon.ico'
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  let [ifShow, setIfShow] = useState(false)
  function handleResize() {
    if ((window.innerWidth <= 640) && (ifShow == true)) {
      setIfShow(false)
      console.log(1);
    }
  }
  useEffect(() => {
    // typeof window !== "undefined" &&
    window.addEventListener('resize', handleResize)
  })
  return (
    <html lang="ru">
      <body className={inter.className}>
        <div className="bg-gray-100 dark:bg-gray-900 text-gray-900 dark:text-white h-full min-h-screen relative overflow-auto">
          {/* <ToastList /> */}
          <div className="flex md:gap-4 gap-0 transition-all">
            <div className="flex-none lg:w-72 sm:w-16 w-0">
                <Sidebar ifShow={ifShow} />
            </div>
            {
              !ifShow ? 
              <div onClick={() => setIfShow(true)} className="sm:hidden fixed text-white bg-gray-800 w-10 h-10 top-3 left-3 rounded-full flex items-center justify-center text-3xl font-semibold cursor-pointer opacity-90 z-[22]"><Plus /></div> :
              <div onClick={() => setIfShow(false)} className='sm:hidden fixed text-white bg-gray-800 w-10 h-10 top-3 right-3 rounded-full flex items-center justify-center text-3xl font-semibold cursor-pointer opacity-90 z-[22]'><Cross /></div>
            }
            <div className="md:mr-8 md:mt-8 md:ml-4 md:mb-8 mr-2 mt-2 ml-2 mb-2 w-full h-fit overflow-auto">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}

function Cross() {
  return (
    <svg viewBox="0 0 512.021 512.021" width="16" height="16">
      <path fill='#9ca3af' d="M301.258,256.01L502.645,54.645c12.501-12.501,12.501-32.769,0-45.269c-12.501-12.501-32.769-12.501-45.269,0l0,0   L256.01,210.762L54.645,9.376c-12.501-12.501-32.769-12.501-45.269,0s-12.501,32.769,0,45.269L210.762,256.01L9.376,457.376   c-12.501,12.501-12.501,32.769,0,45.269s32.769,12.501,45.269,0L256.01,301.258l201.365,201.387   c12.501,12.501,32.769,12.501,45.269,0c12.501-12.501,12.501-32.769,0-45.269L301.258,256.01z"/>
    </svg>
  )
}

function Plus() {
  return (
    <svg viewBox="0 0 512 512" width="20" height="20">
      <path fill='#9ca3af' d="M480,224H288V32c0-17.673-14.327-32-32-32s-32,14.327-32,32v192H32c-17.673,0-32,14.327-32,32s14.327,32,32,32h192v192   c0,17.673,14.327,32,32,32s32-14.327,32-32V288h192c17.673,0,32-14.327,32-32S497.673,224,480,224z"/>
    </svg>
  )
}