import './globals.css'
import { Inter } from 'next/font/google'
import { Sidebar } from '@/components/Sidebar/Sidebar'
import { StoreProvider } from '@/redux/StoreProvider'

const inter = Inter({ subsets: ['cyrillic'] })

export const metadata = {
  title: {
    template: '%s | stfaki',
    default: 'ФАКТ'
  },
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
    shortcut: '/favicon.ico',
    apple: '/favicon.ico'
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={inter.className}>
      <StoreProvider>
        <div className="bg-gray-100 dark:bg-gray-900 text-gray-900 dark:text-white h-full min-h-screen relative overflow-auto">
          {/* <ToastList /> */}
          <div className="flex md:gap-4 gap-0 transition-all">
            <div className="flex-none lg:w-72 sm:w-16 w-0">
                <Sidebar />
            </div>
            <div className="md:mr-8 md:mt-8 md:ml-4 md:mb-8 mr-2 mt-2 ml-2 mb-2 w-full h-fit overflow-auto">
              {children}
            </div>
          </div>
        </div>
        </StoreProvider>
      </body>
    </html>
  )
}